modLoader="kotlinforforge"
loaderVersion="[5.10,)"
issueTrackerURL = "https://github.com/gitoido-mc/conditional-riding/issues"
license='''GPL-3.0-only'''

[[mods]]
modId = "conditional_riding"
version = "${version}"
displayName = "Cobblemon Conditional Riding"
authors = "Gito"
description = '''
Allows to configure ability to ride pokemans via simple config!
'''
logoFile = "assets/conditional_riding/icon.png"

[[dependencies.conditional_riding]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.conditional_riding]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.conditional_riding]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.3,)"
ordering = "AFTER"
side = "BOTH"
